#!/bin/bash -e

if [ "$#" == 0 ]
then
	echo "usage: easydeploy [options] repo
    -c: check if already installed (if alrady installed, dont install again) 
    -u: dont update if already exists a version
    -i: dont install, only update cache" 
	exit 1
fi

OPTCHECK=0
OPTUPDATE=1
OPTINSTALL=1

while getopts "uic:" flag
do
    case $flag in
        c)
	    OPTCHECK=$OPTARG
            ;;
        u)
            OPTUPDATE=0
            ;;
        i)
	    OPTINSTALL=0
            ;;
    esac
done

shift $((OPTIND-1))

REPO=$1
REPOPATH=""

if [ "$#" -gt 1 ] 
then
	REPOPATH=$2
fi

LOCALPATH=/var/local/easydeploy/cache/$REPO
INSTALLEDFILEPATH=/var/local/easydeploy/installed/$REPO 

if [ $OPTCHECK -eq 1 ]  && [ -f $INSTALLEDFILEPATH ]
then
	echo $REPO already installed
	exit 0
fi

export GIT_SSL_NO_VERIFY=true

if [ -d $LOCALPATH ]
then
	cd $LOCALPATH
	if [ $OPTUPDATE -eq 1 ]
	then
		git pull
		git checkout master
	fi
else
	mkdir -p `dirname $LOCALPATH`
	cd `dirname $LOCALPATH`
	git clone git@github.com:$REPO.git 
	cd $LOCALPATH
fi

if [ $OPTINSTALL -eq 1 ]
then
	./install.sh
fi

mkdir -p `dirname $INSTALLEDFILEPATH`
touch $INSTALLEDFILEPATH



